--- #YAML:1.0
name:                Template-Recall
version:             0.15
abstract:            "Reverse callback" templating system
license:             ~
author:              
    - James Robson <gilad@arbingersys.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
